id = "charbox-theme"
name = "Charbox Theme"
version = "0.1.1"
schema_version = 1
authors = ["MONARCH"]
description = "A high-contrast, Gruvbox-inspired Zed theme."
repository = "https://github.com/monarcode/charbox-zed"
